package gkyt.dao;

import gkyt.model.DrawbackLog;
import gkyt.model.DrawbackLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrawbackLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int countByExample(DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int deleteByExample(DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int insert(DrawbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int insertSelective(DrawbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    List<DrawbackLog> selectByExampleWithBLOBs(DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    List<DrawbackLog> selectByExample(DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    DrawbackLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") DrawbackLog record, @Param("example") DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") DrawbackLog record, @Param("example") DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int updateByExample(@Param("record") DrawbackLog record, @Param("example") DrawbackLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int updateByPrimaryKeySelective(DrawbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(DrawbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawback_logs
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    int updateByPrimaryKey(DrawbackLog record);
}