package gkyt.dao;

import gkyt.model.Drawback;
import gkyt.model.DrawbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DrawbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int countByExample(DrawbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int deleteByExample(DrawbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int insert(Drawback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int insertSelective(Drawback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    List<Drawback> selectByExample(DrawbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    Drawback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") Drawback record, @Param("example") DrawbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int updateByExample(@Param("record") Drawback record, @Param("example") DrawbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int updateByPrimaryKeySelective(Drawback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawbacks
     *
     * @mbggenerated Tue Jun 13 17:58:01 CST 2017
     */
    int updateByPrimaryKey(Drawback record);
}