package gkyt.dao;

import gkyt.model.Family;
import gkyt.model.FamilyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FamilyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int countByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int deleteByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int insert(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int insertSelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    List<Family> selectByExample(FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    Family selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int updateByExample(@Param("record") Family record, @Param("example") FamilyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int updateByPrimaryKeySelective(Family record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table families
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    int updateByPrimaryKey(Family record);
}