package gkyt.dao;

import gkyt.model.Jail;
import gkyt.model.JailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int countByExample(JailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int deleteByExample(JailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int insert(Jail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int insertSelective(Jail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    List<Jail> selectByExample(JailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    Jail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") Jail record, @Param("example") JailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int updateByExample(@Param("record") Jail record, @Param("example") JailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int updateByPrimaryKeySelective(Jail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    int updateByPrimaryKey(Jail record);
}