package gkyt.model;

import java.util.Date;

public class DrawbackLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.id
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.drawback_id
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private Integer drawbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.verify_type
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private Byte verifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.verify_user
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private Integer verifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.created_at
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.updated_at
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drawback_logs.verify_msg
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    private String verifyMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.id
     *
     * @return the value of drawback_logs.id
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.id
     *
     * @param id the value for drawback_logs.id
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.drawback_id
     *
     * @return the value of drawback_logs.drawback_id
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public Integer getDrawbackId() {
        return drawbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.drawback_id
     *
     * @param drawbackId the value for drawback_logs.drawback_id
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setDrawbackId(Integer drawbackId) {
        this.drawbackId = drawbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.verify_type
     *
     * @return the value of drawback_logs.verify_type
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public Byte getVerifyType() {
        return verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.verify_type
     *
     * @param verifyType the value for drawback_logs.verify_type
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setVerifyType(Byte verifyType) {
        this.verifyType = verifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.verify_user
     *
     * @return the value of drawback_logs.verify_user
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public Integer getVerifyUser() {
        return verifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.verify_user
     *
     * @param verifyUser the value for drawback_logs.verify_user
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setVerifyUser(Integer verifyUser) {
        this.verifyUser = verifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.created_at
     *
     * @return the value of drawback_logs.created_at
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.created_at
     *
     * @param createdAt the value for drawback_logs.created_at
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.updated_at
     *
     * @return the value of drawback_logs.updated_at
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.updated_at
     *
     * @param updatedAt the value for drawback_logs.updated_at
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drawback_logs.verify_msg
     *
     * @return the value of drawback_logs.verify_msg
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public String getVerifyMsg() {
        return verifyMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drawback_logs.verify_msg
     *
     * @param verifyMsg the value for drawback_logs.verify_msg
     *
     * @mbggenerated Wed Jun 14 15:15:04 CST 2017
     */
    public void setVerifyMsg(String verifyMsg) {
        this.verifyMsg = verifyMsg == null ? null : verifyMsg.trim();
    }
}