package gkyt.model;

import java.math.BigDecimal;
import java.util.Date;

public class Family {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.id
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.prisoner_id
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private Integer prisonerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.name
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.uuid
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.phone
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.relationship
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private String relationship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.created_at
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.updated_at
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.image_url
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.balance
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column families.last_trade_no
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    private String lastTradeNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.id
     *
     * @return the value of families.id
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.id
     *
     * @param id the value for families.id
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.prisoner_id
     *
     * @return the value of families.prisoner_id
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public Integer getPrisonerId() {
        return prisonerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.prisoner_id
     *
     * @param prisonerId the value for families.prisoner_id
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setPrisonerId(Integer prisonerId) {
        this.prisonerId = prisonerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.name
     *
     * @return the value of families.name
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.name
     *
     * @param name the value for families.name
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.uuid
     *
     * @return the value of families.uuid
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.uuid
     *
     * @param uuid the value for families.uuid
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.phone
     *
     * @return the value of families.phone
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.phone
     *
     * @param phone the value for families.phone
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.relationship
     *
     * @return the value of families.relationship
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public String getRelationship() {
        return relationship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.relationship
     *
     * @param relationship the value for families.relationship
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship == null ? null : relationship.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.created_at
     *
     * @return the value of families.created_at
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.created_at
     *
     * @param createdAt the value for families.created_at
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.updated_at
     *
     * @return the value of families.updated_at
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.updated_at
     *
     * @param updatedAt the value for families.updated_at
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.image_url
     *
     * @return the value of families.image_url
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.image_url
     *
     * @param imageUrl the value for families.image_url
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.balance
     *
     * @return the value of families.balance
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.balance
     *
     * @param balance the value for families.balance
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column families.last_trade_no
     *
     * @return the value of families.last_trade_no
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public String getLastTradeNo() {
        return lastTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column families.last_trade_no
     *
     * @param lastTradeNo the value for families.last_trade_no
     *
     * @mbggenerated Fri Jun 09 17:37:27 CST 2017
     */
    public void setLastTradeNo(String lastTradeNo) {
        this.lastTradeNo = lastTradeNo == null ? null : lastTradeNo.trim();
    }
}