package gkyt.model;

import java.util.Date;

public class Jail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.id
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.title
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.description
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.street
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.district
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.city
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.state
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.zipcode
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.accid
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String accid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.created_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.updated_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.image_file_name
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String imageFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.image_content_type
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private String imageContentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.image_file_size
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private Integer imageFileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jails.image_updated_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    private Date imageUpdatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.id
     *
     * @return the value of jails.id
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.id
     *
     * @param id the value for jails.id
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.title
     *
     * @return the value of jails.title
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.title
     *
     * @param title the value for jails.title
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.description
     *
     * @return the value of jails.description
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.description
     *
     * @param description the value for jails.description
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.street
     *
     * @return the value of jails.street
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.street
     *
     * @param street the value for jails.street
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.district
     *
     * @return the value of jails.district
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.district
     *
     * @param district the value for jails.district
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.city
     *
     * @return the value of jails.city
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.city
     *
     * @param city the value for jails.city
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.state
     *
     * @return the value of jails.state
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.state
     *
     * @param state the value for jails.state
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.zipcode
     *
     * @return the value of jails.zipcode
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.zipcode
     *
     * @param zipcode the value for jails.zipcode
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.accid
     *
     * @return the value of jails.accid
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getAccid() {
        return accid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.accid
     *
     * @param accid the value for jails.accid
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setAccid(String accid) {
        this.accid = accid == null ? null : accid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.created_at
     *
     * @return the value of jails.created_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.created_at
     *
     * @param createdAt the value for jails.created_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.updated_at
     *
     * @return the value of jails.updated_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.updated_at
     *
     * @param updatedAt the value for jails.updated_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.image_file_name
     *
     * @return the value of jails.image_file_name
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getImageFileName() {
        return imageFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.image_file_name
     *
     * @param imageFileName the value for jails.image_file_name
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setImageFileName(String imageFileName) {
        this.imageFileName = imageFileName == null ? null : imageFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.image_content_type
     *
     * @return the value of jails.image_content_type
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getImageContentType() {
        return imageContentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.image_content_type
     *
     * @param imageContentType the value for jails.image_content_type
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setImageContentType(String imageContentType) {
        this.imageContentType = imageContentType == null ? null : imageContentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.image_file_size
     *
     * @return the value of jails.image_file_size
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Integer getImageFileSize() {
        return imageFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.image_file_size
     *
     * @param imageFileSize the value for jails.image_file_size
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setImageFileSize(Integer imageFileSize) {
        this.imageFileSize = imageFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jails.image_updated_at
     *
     * @return the value of jails.image_updated_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Date getImageUpdatedAt() {
        return imageUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jails.image_updated_at
     *
     * @param imageUpdatedAt the value for jails.image_updated_at
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setImageUpdatedAt(Date imageUpdatedAt) {
        this.imageUpdatedAt = imageUpdatedAt;
    }
}