package gkyt.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public JailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andStreetIsNull() {
            addCriterion("street is null");
            return (Criteria) this;
        }

        public Criteria andStreetIsNotNull() {
            addCriterion("street is not null");
            return (Criteria) this;
        }

        public Criteria andStreetEqualTo(String value) {
            addCriterion("street =", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotEqualTo(String value) {
            addCriterion("street <>", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetGreaterThan(String value) {
            addCriterion("street >", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetGreaterThanOrEqualTo(String value) {
            addCriterion("street >=", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLessThan(String value) {
            addCriterion("street <", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLessThanOrEqualTo(String value) {
            addCriterion("street <=", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetLike(String value) {
            addCriterion("street like", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotLike(String value) {
            addCriterion("street not like", value, "street");
            return (Criteria) this;
        }

        public Criteria andStreetIn(List<String> values) {
            addCriterion("street in", values, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotIn(List<String> values) {
            addCriterion("street not in", values, "street");
            return (Criteria) this;
        }

        public Criteria andStreetBetween(String value1, String value2) {
            addCriterion("street between", value1, value2, "street");
            return (Criteria) this;
        }

        public Criteria andStreetNotBetween(String value1, String value2) {
            addCriterion("street not between", value1, value2, "street");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNull() {
            addCriterion("district is null");
            return (Criteria) this;
        }

        public Criteria andDistrictIsNotNull() {
            addCriterion("district is not null");
            return (Criteria) this;
        }

        public Criteria andDistrictEqualTo(String value) {
            addCriterion("district =", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotEqualTo(String value) {
            addCriterion("district <>", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThan(String value) {
            addCriterion("district >", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictGreaterThanOrEqualTo(String value) {
            addCriterion("district >=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThan(String value) {
            addCriterion("district <", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLessThanOrEqualTo(String value) {
            addCriterion("district <=", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictLike(String value) {
            addCriterion("district like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotLike(String value) {
            addCriterion("district not like", value, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictIn(List<String> values) {
            addCriterion("district in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotIn(List<String> values) {
            addCriterion("district not in", values, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictBetween(String value1, String value2) {
            addCriterion("district between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andDistrictNotBetween(String value1, String value2) {
            addCriterion("district not between", value1, value2, "district");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNull() {
            addCriterion("zipcode is null");
            return (Criteria) this;
        }

        public Criteria andZipcodeIsNotNull() {
            addCriterion("zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andZipcodeEqualTo(String value) {
            addCriterion("zipcode =", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotEqualTo(String value) {
            addCriterion("zipcode <>", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThan(String value) {
            addCriterion("zipcode >", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("zipcode >=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThan(String value) {
            addCriterion("zipcode <", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLessThanOrEqualTo(String value) {
            addCriterion("zipcode <=", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeLike(String value) {
            addCriterion("zipcode like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotLike(String value) {
            addCriterion("zipcode not like", value, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeIn(List<String> values) {
            addCriterion("zipcode in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotIn(List<String> values) {
            addCriterion("zipcode not in", values, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeBetween(String value1, String value2) {
            addCriterion("zipcode between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andZipcodeNotBetween(String value1, String value2) {
            addCriterion("zipcode not between", value1, value2, "zipcode");
            return (Criteria) this;
        }

        public Criteria andAccidIsNull() {
            addCriterion("accid is null");
            return (Criteria) this;
        }

        public Criteria andAccidIsNotNull() {
            addCriterion("accid is not null");
            return (Criteria) this;
        }

        public Criteria andAccidEqualTo(String value) {
            addCriterion("accid =", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotEqualTo(String value) {
            addCriterion("accid <>", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidGreaterThan(String value) {
            addCriterion("accid >", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidGreaterThanOrEqualTo(String value) {
            addCriterion("accid >=", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidLessThan(String value) {
            addCriterion("accid <", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidLessThanOrEqualTo(String value) {
            addCriterion("accid <=", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidLike(String value) {
            addCriterion("accid like", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotLike(String value) {
            addCriterion("accid not like", value, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidIn(List<String> values) {
            addCriterion("accid in", values, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotIn(List<String> values) {
            addCriterion("accid not in", values, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidBetween(String value1, String value2) {
            addCriterion("accid between", value1, value2, "accid");
            return (Criteria) this;
        }

        public Criteria andAccidNotBetween(String value1, String value2) {
            addCriterion("accid not between", value1, value2, "accid");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andImageFileNameIsNull() {
            addCriterion("image_file_name is null");
            return (Criteria) this;
        }

        public Criteria andImageFileNameIsNotNull() {
            addCriterion("image_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andImageFileNameEqualTo(String value) {
            addCriterion("image_file_name =", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameNotEqualTo(String value) {
            addCriterion("image_file_name <>", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameGreaterThan(String value) {
            addCriterion("image_file_name >", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("image_file_name >=", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameLessThan(String value) {
            addCriterion("image_file_name <", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameLessThanOrEqualTo(String value) {
            addCriterion("image_file_name <=", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameLike(String value) {
            addCriterion("image_file_name like", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameNotLike(String value) {
            addCriterion("image_file_name not like", value, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameIn(List<String> values) {
            addCriterion("image_file_name in", values, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameNotIn(List<String> values) {
            addCriterion("image_file_name not in", values, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameBetween(String value1, String value2) {
            addCriterion("image_file_name between", value1, value2, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageFileNameNotBetween(String value1, String value2) {
            addCriterion("image_file_name not between", value1, value2, "imageFileName");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeIsNull() {
            addCriterion("image_content_type is null");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeIsNotNull() {
            addCriterion("image_content_type is not null");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeEqualTo(String value) {
            addCriterion("image_content_type =", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeNotEqualTo(String value) {
            addCriterion("image_content_type <>", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeGreaterThan(String value) {
            addCriterion("image_content_type >", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeGreaterThanOrEqualTo(String value) {
            addCriterion("image_content_type >=", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeLessThan(String value) {
            addCriterion("image_content_type <", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeLessThanOrEqualTo(String value) {
            addCriterion("image_content_type <=", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeLike(String value) {
            addCriterion("image_content_type like", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeNotLike(String value) {
            addCriterion("image_content_type not like", value, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeIn(List<String> values) {
            addCriterion("image_content_type in", values, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeNotIn(List<String> values) {
            addCriterion("image_content_type not in", values, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeBetween(String value1, String value2) {
            addCriterion("image_content_type between", value1, value2, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageContentTypeNotBetween(String value1, String value2) {
            addCriterion("image_content_type not between", value1, value2, "imageContentType");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeIsNull() {
            addCriterion("image_file_size is null");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeIsNotNull() {
            addCriterion("image_file_size is not null");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeEqualTo(Integer value) {
            addCriterion("image_file_size =", value, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeNotEqualTo(Integer value) {
            addCriterion("image_file_size <>", value, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeGreaterThan(Integer value) {
            addCriterion("image_file_size >", value, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeGreaterThanOrEqualTo(Integer value) {
            addCriterion("image_file_size >=", value, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeLessThan(Integer value) {
            addCriterion("image_file_size <", value, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeLessThanOrEqualTo(Integer value) {
            addCriterion("image_file_size <=", value, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeIn(List<Integer> values) {
            addCriterion("image_file_size in", values, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeNotIn(List<Integer> values) {
            addCriterion("image_file_size not in", values, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeBetween(Integer value1, Integer value2) {
            addCriterion("image_file_size between", value1, value2, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageFileSizeNotBetween(Integer value1, Integer value2) {
            addCriterion("image_file_size not between", value1, value2, "imageFileSize");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtIsNull() {
            addCriterion("image_updated_at is null");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtIsNotNull() {
            addCriterion("image_updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtEqualTo(Date value) {
            addCriterion("image_updated_at =", value, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtNotEqualTo(Date value) {
            addCriterion("image_updated_at <>", value, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtGreaterThan(Date value) {
            addCriterion("image_updated_at >", value, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("image_updated_at >=", value, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtLessThan(Date value) {
            addCriterion("image_updated_at <", value, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("image_updated_at <=", value, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtIn(List<Date> values) {
            addCriterion("image_updated_at in", values, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtNotIn(List<Date> values) {
            addCriterion("image_updated_at not in", values, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("image_updated_at between", value1, value2, "imageUpdatedAt");
            return (Criteria) this;
        }

        public Criteria andImageUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("image_updated_at not between", value1, value2, "imageUpdatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jails
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 08 09:18:17 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jails
     *
     * @mbggenerated Thu Jun 08 09:18:17 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}